
use `bd-cad-paciente`;

INSERT INTO counties(ibge,name,fu) VALUES (510010,'ACORIZAL','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510020,'ÁGUA BOA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510025,'ALTA FLORESTA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510030,'ALTO ARAGUAIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510035,'ALTO BOA VISTA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510040,'ALTO GARÇAS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510050,'ALTO PARAGUAI','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510060,'ALTO TAQUARI','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510080,'APIACÁS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510100,'ARAGUAIANA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510120,'ARAGUAINHA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510125,'ARAPUTANGA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510130,'ARENÁPOLIS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510140,'ARIPUANA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510160,'BARÃO DE MELGAÇO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510170,'BARRA DO BUGRES','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510180,'BARRA DO GARÇAS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510185,'BOM JESUS DO ARAGUAIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510190,'BRASNORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510250,'CÁCERES','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510260,'CAMPINÁPOLIS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510263,'CAMPO NOVO DO PARECIS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510267,'CAMPO VERDE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510268,'CAMPOS DE JÚLIO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510269,'CANABRAVA DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510270,'CANARANA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510279,'CARLINDA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510285,'CASTANHEIRA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510300,'CHAPADA DOS GUIMARÃES','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510305,'CLAUDIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510310,'COCALINHO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510320,'COLÍDER','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510325,'COLNIZA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510330,'COMODORO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510335,'CONFRESA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510336,'CONQUISTA D''OESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510337,'COTRIGUAÇU','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510340,'CUIABÁ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510343,'CURVELÂNDIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510345,'DENISE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510350,'DIAMANTINO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510360,'DOM AQUINO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510370,'FELIZ NATAL','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510380,'FIGUEIRÓPOLIS D''OESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510385,'GAÚCHA DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510390,'GENERAL CARNEIRO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510395,'GLÓRIA D''OESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510410,'GUARANTÃ DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510420,'GUIRATINGA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510450,'INDIAVAÍ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510452,'IPIRANGA DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510454,'ITANHANGÁ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510455,'ITAÚBA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510460,'ITIQUIRA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510480,'JACIARA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510490,'JANGADA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510500,'JAURU','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510510,'JUARA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510515,'JUÍNA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510517,'JURUENA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510520,'JUSCIMEIRA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510523,'LAMBARI D''OESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510525,'LUCAS DO RIO VERDE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510530,'LUCIARA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510558,'MARCELÂNDIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510560,'MATUPÁ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510562,'MIRASSOL D''OESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510590,'NOBRES','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510600,'NORTELÂNDIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510610,'NOSSA SENHORA DO LIVRAMENTO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510615,'NOVA BANDEIRANTES','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510620,'NOVA BRASILÂNDIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510621,'NOVA CANAÃ DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510880,'NOVA GUARITA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510618,'NOVA LACERDA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510885,'NOVA MARILÂNDIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510890,'NOVA MARINGÁ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510895,'NOVA MONTE VERDE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510622,'NOVA MUTUM','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510617,'NOVA NAZARÁ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510623,'NOVA OLÍMPIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510619,'NOVA SANTA HELENA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510624,'NOVA UBIRATÃ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510625,'NOVA XAVANTINA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510627,'NOVO HORIZONTE DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510626,'NOVO MUNDO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510631,'NOVO SANTO ANTÔNIO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510628,'NOVO SÃO JOAQUIM','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510629,'PARANAÍTA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510630,'PARANATINGA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510637,'PEDRA PRETA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510642,'PEIXOTO DE AZEVEDO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510645,'PLANALTO DA SERRA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510650,'POCONÉ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510665,'PONTAL DO ARAGUAIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510670,'PONTE BRANCA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510675,'PONTES E LACERDA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510677,'PORTO ALEGRE DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510680,'PORTO DOS GAÚCHOS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510682,'PORTO ESPERIDIÃO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510685,'PORTO ESTRELA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510700,'POXORÉU','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510704,'PRIMAVERA DO LESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510706,'QUERÊNCIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510715,'RESERVA DO CABAÇAL','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510718,'RIBEIRÃO CASCALHEIRA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510719,'RIBEIRÃOZINHO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510720,'RIO BRANCO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510757,'RONDOLÂNDIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510760,'RONDONÓPOLIS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510770,'ROSÁRIO OESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510775,'SALTO DO CÉU','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510724,'SANTA CARMEM','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510774,'SANTA CRUZ DO XINGU','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510776,'SANTA RITA DO TRIVELATO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510777,'SANTA TEREZINHA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510726,'SANTO AFONSO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510779,'SANTO ANTÔNIO DO LESTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510780,'SANTO ANTÔNIO DO LEVERGER','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510785,'SÃO FÉLIX DO ARAGUAIA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510729,'SÃO JOSÉ DO POVO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510730,'SÃO JOSÉ DO RIO CLARO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510735,'SÃO JOSÉ DO XINGU','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510710,'SÃO JOSÉ DOS QUATRO MARCOS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510740,'SÃO PEDRO DA CIPA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510787,'SAPEZAL','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510788,'SERRA NOVA DOURADA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510790,'SINOP','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510792,'SORRISO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510794,'TABAPORÃ','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510795,'TANGARÁ DA SERRA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510800,'TAPURAH','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510805,'TERRA NOVA DO NORTE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510810,'TESOURO','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510820,'TORIXORÉU','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510830,'UNIÃO DO SUL','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510835,'VALE DE SÃO DOMINGOS','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510840,'VÁRZEA GRANDE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510850,'VERA','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510550,'VILA BELA DA SANTÍSSIMA TRINDADE','MT');
INSERT INTO counties(ibge,name,fu) VALUES (510860,'VILA RICA','MT');
